const fc = require('fast-check');
const { generateContentPlan, validateContentPlan, initializeGemini } = require('./aiService');

describe('AI Service - Property Tests', () => {
    /**
     * Property 4: Content Plan Structure Validation
     * Validates: Requirements 3.2, 3.3
     * 
     * For any content plan generated by the AI service, it must contain all required
     * fields (format, topic, caption, media_prompt, ai_analysis) with valid values.
     */
    test('Feature: ai-social-media-manager, Property 4: Content plan structure validation', () => {
        fc.assert(
            fc.property(
                fc.record({
                    format: fc.constantFrom('post', 'reel', 'story'),
                    topic: fc.string({ minLength: 1, maxLength: 100 }).filter(s => s.trim().length > 0),
                    caption: fc.string({ minLength: 1, maxLength: 500 }).filter(s => s.trim().length > 0),
                    media_prompt: fc.string({ minLength: 1, maxLength: 200 }).filter(s => s.trim().length > 0),
                    ai_analysis: fc.string({ minLength: 1, maxLength: 200 }).filter(s => s.trim().length > 0)
                }),
                (plan) => {
                    // Validate the content plan structure
                    const validatedPlan = validateContentPlan(plan);
                    
                    // Verify all required fields are present
                    expect(validatedPlan).toHaveProperty('format');
                    expect(validatedPlan).toHaveProperty('topic');
                    expect(validatedPlan).toHaveProperty('caption');
                    expect(validatedPlan).toHaveProperty('media_prompt');
                    expect(validatedPlan).toHaveProperty('ai_analysis');
                    
                    // Verify values are not empty
                    expect(validatedPlan.format).toBeTruthy();
                    expect(validatedPlan.topic).toBeTruthy();
                    expect(validatedPlan.caption).toBeTruthy();
                    expect(validatedPlan.media_prompt).toBeTruthy();
                    expect(validatedPlan.ai_analysis).toBeTruthy();
                }
            ),
            { numRuns: 100 }
        );
    });

    /**
     * Property 5: Format Enumeration Validation
     * Validates: Requirements 3.4
     * 
     * For any content plan, the format field must be one of the valid enumerated
     * values: 'post', 'reel', or 'story'.
     */
    test('Feature: ai-social-media-manager, Property 5: Format enumeration validation', () => {
        fc.assert(
            fc.property(
                fc.record({
                    format: fc.constantFrom('post', 'reel', 'story'),
                    topic: fc.string({ minLength: 1, maxLength: 100 }).filter(s => s.trim().length > 0),
                    caption: fc.string({ minLength: 1, maxLength: 500 }).filter(s => s.trim().length > 0),
                    media_prompt: fc.string({ minLength: 1, maxLength: 200 }).filter(s => s.trim().length > 0),
                    ai_analysis: fc.string({ minLength: 1, maxLength: 200 }).filter(s => s.trim().length > 0)
                }),
                (plan) => {
                    // Validate the content plan
                    const validatedPlan = validateContentPlan(plan);
                    
                    // Verify format is one of the valid enumerated values
                    const validFormats = ['post', 'reel', 'story'];
                    expect(validFormats).toContain(validatedPlan.format);
                }
            ),
            { numRuns: 100 }
        );
    });

    /**
     * Property Test: Invalid format should be rejected
     * Validates: Requirements 3.4
     */
    test('Feature: ai-social-media-manager, Property 5: Invalid format enumeration rejection', () => {
        fc.assert(
            fc.property(
                fc.record({
                    format: fc.string({ minLength: 1 }).filter(s => s.trim().length > 0 && !['post', 'reel', 'story'].includes(s)),
                    topic: fc.string({ minLength: 1, maxLength: 100 }).filter(s => s.trim().length > 0),
                    caption: fc.string({ minLength: 1, maxLength: 500 }).filter(s => s.trim().length > 0),
                    media_prompt: fc.string({ minLength: 1, maxLength: 200 }).filter(s => s.trim().length > 0),
                    ai_analysis: fc.string({ minLength: 1, maxLength: 200 }).filter(s => s.trim().length > 0)
                }),
                (plan) => {
                    // Validation should throw an error for invalid format
                    expect(() => validateContentPlan(plan)).toThrow(/Invalid format/);
                }
            ),
            { numRuns: 100 }
        );
    });

    /**
     * Property Test: Missing required fields should be rejected
     * Validates: Requirements 3.3
     */
    test('Feature: ai-social-media-manager, Property 4: Missing required fields rejection', () => {
        fc.assert(
            fc.property(
                fc.record({
                    format: fc.constantFrom('post', 'reel', 'story'),
                    topic: fc.string({ minLength: 1, maxLength: 100 }).filter(s => s.trim().length > 0),
                    caption: fc.string({ minLength: 1, maxLength: 500 }).filter(s => s.trim().length > 0),
                    media_prompt: fc.string({ minLength: 1, maxLength: 200 }).filter(s => s.trim().length > 0),
                    ai_analysis: fc.string({ minLength: 1, maxLength: 200 }).filter(s => s.trim().length > 0)
                }),
                fc.constantFrom('format', 'topic', 'caption', 'media_prompt', 'ai_analysis'),
                (plan, fieldToRemove) => {
                    // Create a plan with one required field missing
                    const incompletePlan = { ...plan };
                    delete incompletePlan[fieldToRemove];
                    
                    // Validation should throw an error for missing field
                    expect(() => validateContentPlan(incompletePlan)).toThrow(/missing required fields/);
                }
            ),
            { numRuns: 100 }
        );
    });
});

describe('AI Service - Unit Tests', () => {
    /**
     * Unit Test: validateContentPlan accepts valid plan
     * Validates: Requirements 3.3, 3.4
     */
    test('should accept valid content plan with all required fields', () => {
        const validPlan = {
            format: 'post',
            topic: 'Social Media Tips',
            caption: 'Check out these amazing tips!',
            media_prompt: 'A vibrant social media graphic',
            ai_analysis: 'Posts perform well based on historical data'
        };

        const result = validateContentPlan(validPlan);
        
        expect(result).toEqual(validPlan);
    });

    /**
     * Unit Test: validateContentPlan rejects plan with missing format
     * Validates: Requirements 3.3
     */
    test('should reject plan missing format field', () => {
        const invalidPlan = {
            topic: 'Social Media Tips',
            caption: 'Check out these amazing tips!',
            media_prompt: 'A vibrant social media graphic',
            ai_analysis: 'Posts perform well based on historical data'
        };

        expect(() => validateContentPlan(invalidPlan)).toThrow('Content plan missing required fields: format');
    });

    /**
     * Unit Test: validateContentPlan rejects plan with missing multiple fields
     * Validates: Requirements 3.3
     */
    test('should reject plan missing multiple fields', () => {
        const invalidPlan = {
            format: 'post',
            caption: 'Check out these amazing tips!'
        };

        expect(() => validateContentPlan(invalidPlan)).toThrow('Content plan missing required fields: topic, media_prompt, ai_analysis');
    });

    /**
     * Unit Test: validateContentPlan rejects invalid format
     * Validates: Requirements 3.4
     */
    test('should reject plan with invalid format', () => {
        const invalidPlan = {
            format: 'video',
            topic: 'Social Media Tips',
            caption: 'Check out these amazing tips!',
            media_prompt: 'A vibrant social media graphic',
            ai_analysis: 'Posts perform well based on historical data'
        };

        expect(() => validateContentPlan(invalidPlan)).toThrow("Invalid format 'video'. Must be one of: post, reel, story");
    });

    /**
     * Unit Test: validateContentPlan accepts all valid formats
     * Validates: Requirements 3.4
     */
    test('should accept all valid format types', () => {
        const validFormats = ['post', 'reel', 'story'];

        validFormats.forEach(format => {
            const plan = {
                format: format,
                topic: 'Test Topic',
                caption: 'Test Caption',
                media_prompt: 'Test Prompt',
                ai_analysis: 'Test Analysis'
            };

            expect(() => validateContentPlan(plan)).not.toThrow();
        });
    });

    /**
     * Unit Test: initializeGemini throws error when API key is missing
     * Validates: Requirements 11.2, 11.4
     */
    test('should throw error when GEMINI_API_KEY is missing', () => {
        // Save original API key
        const originalApiKey = process.env.GEMINI_API_KEY;
        
        // Remove API key
        delete process.env.GEMINI_API_KEY;

        expect(() => initializeGemini()).toThrow('GEMINI_API_KEY environment variable is required');

        // Restore original API key
        if (originalApiKey) {
            process.env.GEMINI_API_KEY = originalApiKey;
        }
    });
});

describe('AI Service - Error Handling Unit Tests', () => {
    let originalApiKey;

    beforeEach(() => {
        // Save and set a mock API key for testing
        originalApiKey = process.env.GEMINI_API_KEY;
        process.env.GEMINI_API_KEY = 'test_api_key_for_unit_tests';
        
        // Clear any module cache to ensure fresh imports
        jest.resetModules();
    });

    afterEach(() => {
        // Restore original API key
        if (originalApiKey) {
            process.env.GEMINI_API_KEY = originalApiKey;
        } else {
            delete process.env.GEMINI_API_KEY;
        }
        
        // Restore all mocks
        jest.restoreAllMocks();
    });

    /**
     * Unit Test: Error logging includes stack trace
     * Validates: Requirements 12.2
     */
    test('should log error with stack trace when API call fails', async () => {
        // Mock console.error to capture logs
        const originalConsoleError = console.error;
        const errorLogs = [];
        console.error = jest.fn((...args) => errorLogs.push(args.join(' ')));

        // Re-import the module to get fresh instance
        const aiService = require('./aiService');
        
        // Mock the Gemini API to throw an error
        const { GoogleGenerativeAI } = require('@google/generative-ai');
        const mockGenerateContent = jest.fn().mockRejectedValue(new Error('API connection failed'));
        
        jest.spyOn(GoogleGenerativeAI.prototype, 'getGenerativeModel').mockReturnValue({
            generateContent: mockGenerateContent
        });

        try {
            await aiService.generateContentPlan([]);
        } catch (error) {
            // Expected to throw after retries
        }

        // Verify error was logged with message
        expect(errorLogs.some(log => log.includes('✗ AI service error:'))).toBe(true);
        expect(errorLogs.some(log => log.includes('API connection failed'))).toBe(true);
        
        // Verify stack trace was logged
        expect(errorLogs.some(log => log.includes('Error:'))).toBe(true);

        // Restore console.error
        console.error = originalConsoleError;
    }, 10000);

    /**
     * Unit Test: Invalid JSON response triggers retry
     * Validates: Requirements 3.6
     */
    test('should retry once when AI returns invalid JSON', async () => {
        // Mock console.log to capture retry message
        const originalConsoleLog = console.log;
        const logs = [];
        console.log = jest.fn((...args) => logs.push(args.join(' ')));

        // Re-import the module to get fresh instance
        const aiService = require('./aiService');
        
        // Mock the Gemini API to return invalid JSON on first call, valid on second
        const { GoogleGenerativeAI } = require('@google/generative-ai');
        let callCount = 0;
        const mockGenerateContent = jest.fn().mockImplementation(() => {
            callCount++;
            if (callCount === 1) {
                // First call: return invalid JSON
                return Promise.resolve({
                    response: {
                        text: () => 'This is not valid JSON'
                    }
                });
            } else {
                // Second call: return valid JSON
                return Promise.resolve({
                    response: {
                        text: () => JSON.stringify({
                            format: 'post',
                            topic: 'Test Topic',
                            caption: 'Test Caption',
                            media_prompt: 'Test Prompt',
                            ai_analysis: 'Test Analysis'
                        })
                    }
                });
            }
        });
        
        jest.spyOn(GoogleGenerativeAI.prototype, 'getGenerativeModel').mockReturnValue({
            generateContent: mockGenerateContent
        });

        const result = await aiService.generateContentPlan([]);

        // Verify retry was triggered
        expect(logs.some(log => log.includes('↻ Retrying AI content generation...'))).toBe(true);
        
        // Verify the function was called twice (initial + 1 retry)
        expect(mockGenerateContent).toHaveBeenCalledTimes(2);
        
        // Verify final result is valid
        expect(result.format).toBe('post');

        // Restore console.log
        console.log = originalConsoleLog;
    }, 10000);

    /**
     * Unit Test: Retry exhaustion throws error
     * Validates: Requirements 3.6
     */
    test('should throw error after retry exhaustion', async () => {
        // Re-import the module to get fresh instance
        const aiService = require('./aiService');
        
        // Mock the Gemini API to always return invalid JSON
        const { GoogleGenerativeAI } = require('@google/generative-ai');
        const mockGenerateContent = jest.fn().mockResolvedValue({
            response: {
                text: () => 'This is not valid JSON'
            }
        });
        
        jest.spyOn(GoogleGenerativeAI.prototype, 'getGenerativeModel').mockReturnValue({
            generateContent: mockGenerateContent
        });

        // Expect the function to throw after retries are exhausted
        await expect(aiService.generateContentPlan([])).rejects.toThrow('Invalid JSON response from AI');
        
        // Verify the function was called twice (initial + 1 retry)
        expect(mockGenerateContent).toHaveBeenCalledTimes(2);
    }, 10000);
});
